### PR TITLE
Building image for 2.0.16

### PR DESCRIPTION
**Pull request by blauret**
This is an update to the Dockerfile to build the image for 2.0.16

### CODE REVIEW

**Comment by jenswet** [comment]
Thanks @blauret. I've created a release: https://github.com/jenswet/docker-smartsnippets-studio/releases/tag/2.0.16

Docker is building the image, it should be available in a few minutes.

**Comment by blauret** [comment]
I'm already diverging a bit from that PR as I need python-pip. See [this PR](https://github.com/dialog-semiconductor/BLE_SDK10_examples/pull/8).

I'm currently checking if we can have an official Dialog image on dockerhub. For now I'm sharing my flavor [here](https://hub.docker.com/repository/docker/benlauret/smartsnippetsstudio)

**Comment by jenswet** [comment]
Hi @blauret, having an official image on the Docker Hub would be great! Thanks for working on this!

**Comment by blauret** [comment]
@jenswet , 

It's here: https://hub.docker.com/repository/docker/diasemi/smartsnippetsstudio

**Pull request merged**
